name: 'Mise'
description: 'Reusable workflow to invoke a mise action'
inputs:
  java-version:
    description: 'The version of Java to use'
    required: false
    default: 'temurin-17'

runs:
  using: "composite"
  steps:
    - name: Configure Mise
      uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
      with:
        version: 2025.7.12
        mise_toml: |
          [tools]
          yarn= "3.6.3"
          node = "18"
          java = "${{ inputs.java-version }}"

